### ISSUE TITLE
Control with NightShift toggle doesn't respect NightShift state

### ISSUE THREAD

**Issue by thefowles1** [Sticktron/DarkMessages#31]
As of 1.1.3 beta 4, the toggle for allowing the tweak to be automatically controlled by NightShift does not respect the state of NightShift and instead keeps the tweak enabled 24/7. This didn't occur with 1.1.2. Observe the GIF below showing that NightShift is off (I have it set for sunrise/sunset), yet the dark mode toggle stays enabled and re-enables with the NightShift toggle on. 

![img_0458](https://cloud.githubusercontent.com/assets/1276319/24301864/af9ebd68-107e-11e7-96c0-121b668c6d7b.GIF)

**Comment by Sticktron** [comment]
are you using Yalu1011 on an iPhone 7?

**Comment by Sticktron** [comment]
This should be working now as of 1.1.3~b5

**Comment by thefowles1** [comment]
I am using Yalu102 b7 on an iPhone SE. I will try the update in a little while and report back. Thank you for your continuous communication and effort.

**Comment by thefowles1** [comment]
Updated to 1.1.3 beta5-1 and it still doesn't respect the NightShift state on my device. It does ask to restart the messages app, however it remains dark themed even with NightShift turned off.

![pleasantnastyhochstettersfrog-size_restricted](https://cloud.githubusercontent.com/assets/1276319/24313325/5d4e52ae-10aa-11e7-82ee-87cb855b38a5.gif)

**Comment by Sticktron** [comment]
Damn. I had hoped that moving the night shift detection to SpringBoard instead of backboard would solve the issue :(

I'm afraid there is nothing else I can do at this point. I don't have an iPhone 7 or any device on yalu1011 to test with.

**Comment by thefowles1** [comment]
I don't use either of those; I'm on an iPhone SE on 10.2.

It worked before, in version 1.1.2. Did anything about the toggle respect change?

**Comment by Sticktron** [comment]
Oh ok, that's interesting. I thought this was related to yalu1011.

Yes there was a change from 1.1.2 - 1.1.3, and then another change in 1.1.3b5. So it worked for you originally eh?

Would you be interested in helping me test a debug version? Are you able to use deviceconsole, Xcode, or some other way to see the logging information in realtime?

**Comment by thefowles1** [comment]
I, uh, have no idea what any of those are. I'm a novice at best when it comes to tweak development/debugging. But I will test for you if you'd like.

**Comment by Sticktron** [comment]
That's ok :). I'll see what I can do from here.
